const LOCAL_DESK_FOOTER =
  '_Last resort: local documentation desk. Assembled from indexed Help Center, API support guides, and Open API contracts — not generated by a model._';

function excerpt(text, max = 520) {
  const value = String(text || '')
    .replace(/\s+/g, ' ')
    .trim();
  if (!value) return '';
  if (value.length <= max) return value;
  const cut = value.slice(0, max);
  const lastStop = Math.max(cut.lastIndexOf('. '), cut.lastIndexOf('; '));
  const body = (lastStop > 140 ? cut.slice(0, lastStop + 1) : cut).trim();
  return `${body}…`;
}

function uniqueNames(names, limit = 18) {
  return [...new Set((names || []).filter(Boolean))].slice(0, limit);
}

function resolveSchema(schema, schemas, depth = 0, seen = new Set()) {
  if (!schema || typeof schema !== 'object' || depth > 3) return null;
  const ref = typeof schema.$ref === 'string' ? schema.$ref : schema._ref;
  if (typeof ref === 'string') {
    const name = ref.split('/').pop();
    if (!name || seen.has(name)) return schemas?.[name] || null;
    seen.add(name);
    return resolveSchema(schemas?.[name], schemas, depth + 1, seen);
  }
  if (schema.items) return resolveSchema(schema.items, schemas, depth + 1, seen);
  return schema;
}

function jsonSchemaFromContent(content) {
  if (!content || typeof content !== 'object') return null;
  const json =
    content['application/json'] ||
    content['application/json-patch+json'] ||
    content['application/*+json'] ||
    Object.values(content)[0];
  return json?.schema || null;
}

function schemaFromEnvelope(node) {
  if (!node || typeof node !== 'object') return null;
  if (node.schema) return node.schema;
  if (node.content) return jsonSchemaFromContent(node.content);
  return null;
}

function collectPropertyNames(schema, schemas, depth = 0, seen = new Set()) {
  const resolved = resolveSchema(schema, schemas, depth, seen);
  if (!resolved) return [];
  const names = Object.keys(resolved.properties || {});
  for (const key of ['allOf', 'oneOf', 'anyOf']) {
    if (!Array.isArray(resolved[key])) continue;
    resolved[key].forEach((part) => {
      names.push(...collectPropertyNames(part, schemas, depth + 1, seen));
    });
  }
  return uniqueNames(names);
}

function requestFieldNames(operation, schemas) {
  const schema = schemaFromEnvelope(operation?.requestBody);
  const names = collectPropertyNames(schema, schemas);
  if (names.length) return names;
  return uniqueNames((operation?.parameters || []).map((param) => param?.name));
}

function responseFieldNames(operation, schemas) {
  const responses = operation?.responses || {};
  const preferred =
    responses['200'] ||
    responses['201'] ||
    responses['202'] ||
    responses.default ||
    Object.values(responses)[0];
  return collectPropertyNames(schemaFromEnvelope(preferred), schemas);
}

function findOperation(document, method, path) {
  const methods = document?.paths?.[path] || {};
  const key = Object.keys(methods).find((name) => name.toLowerCase() === String(method || '').toLowerCase());
  return key ? methods[key] : null;
}

function formatHelp(articles) {
  if (!articles.length) return '';
  const blocks = articles.slice(0, 4).map((article) => {
    const link = article.url ? ` — [Open article](${article.url})` : '';
    const body = excerpt(article.content);
    return `### ${article.title || 'Help Center'} \`${article.sourceId}\`${link}\n\n${body}`;
  });
  return `## Workflow (Help Center)\n\n${blocks.join('\n\n')}`;
}

function formatKnowledge(articles) {
  if (!articles.length) return '';
  const blocks = articles.slice(0, 3).map((article) => {
    const originLabel = String(article.origin || '')
      .replace(/^Magna-Tiles\s*(?:\/\s*)?/i, '')
      .trim();
    const origin = originLabel ? ` · ${originLabel}` : '';
    const body = excerpt(article.content, 640);
    return `### ${article.title || 'Guide'} \`${article.sourceId}\`${origin}\n\n${body}`;
  });
  return `## Implementation notes (API support guides)\n\n${blocks.join('\n\n')}`;
}

function formatApi(sources) {
  const operations = sources?.swagger?.sources || [];
  if (!operations.length) return '';
  const document = sources?.swagger?.document || {};
  const schemas = document.components?.schemas || {};
  const blocks = operations.slice(0, 5).map((item) => {
    const operation = findOperation(document, item.method, item.path) || {};
    const request = requestFieldNames(operation, schemas);
    const response = responseFieldNames(operation, schemas);
    const summary = excerpt(item.summary || operation.summary || '', 240);
    const requestLine = request.length
      ? `\n- **Request fields:** ${request.map((name) => `\`${name}\``).join(', ')}`
      : '';
    const responseLine = response.length
      ? `\n- **Response fields:** ${response.map((name) => `\`${name}\``).join(', ')}`
      : '';
    return `### \`${item.method} ${item.path}\` \`${item.sourceId}\`\n\n${summary}${requestLine}${responseLine}`;
  });
  return `## Open API contracts\n\n${blocks.join('\n\n')}`;
}

/**
 * Last-resort answer when Gemini and Pollinations cannot respond.
 * Stitches the already-retrieved local index into a readable briefing.
 */
export function generateLocalDeskBriefing(question, sources = {}) {
  const help = sources.helpCenter || [];
  const knowledge = sources.knowledge || [];
  const api = sources.swagger?.sources || [];
  const hasHits = help.length + knowledge.length + api.length > 0;
  const asked = String(question || '').trim() || sources.query || 'your question';

  const sections = [
    'Gemini and Pollinations could not produce an answer, so AIntegration opened the **local documentation desk**.',
    `**Your question:** ${asked}`,
    hasHits
      ? 'This briefing is extracted from the closest indexed sources. Treat it as a reading list with contracts, not a free-form model reply.'
      : 'The local index did not return a strong match. Try a Logiwa screen name, an endpoint path such as `/v3.1/ShipmentOrder`, or a field name.',
    formatHelp(help),
    formatKnowledge(knowledge),
    formatApi(sources),
    'When Gemini or Pollinations is available again, ask the same question for a synthesized walkthrough. Until then, the contracts and citations above are the safest ground truth.',
    LOCAL_DESK_FOOTER,
  ].filter(Boolean);

  return sections.join('\n\n');
}
